version: '3.11'

services:

  redis:
    image: redis
    ports:
      - '6380:6379'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]


  db:
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata/
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
#      - db
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO
    depends_on:
      - redis
      - app
      - celery


volumes:
  pg_data: